name: Build Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Consul Dataplane version (default latest available version)"
        required: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write


    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set tag from action input
        if: ${{ github.event.inputs.tag }}
        run: echo "image_tag=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Set tag from src repo
        if: ${{ !github.event.inputs.tag }}
        run: |
          echo image_tag=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/hashicorp/consul-dataplane/releases | jq -r .[0].tag_name) | tr -d v >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.image_tag }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: IMAGE_TAG=${{ env.image_tag }}
      
